introlab/rtabmap_ros

CMakeLists.txt
package.xml

I'm running ROS kinetic on ubuntu 16.04.
1. I'm currently running a setup on a mobile base without a wheel encoder. This probably not the most common use-case, but the deployed package (0.17.0-1, installed through `apt`) does not contain the `icp_odometry` node that is required to run the demo at `launch/demo/demo_hector_mapping` with `hector:=false`. I was trying to go by the setup described in section 2.3 of [this link](http://wiki.ros.org/rtabmap_ros/Tutorials/SetupOnYourRobot), which lists `icp_odometry` as an option for a setup that is very similar to mine (an RGB-D sensor and a 2D laser). The fix includes the node as an install target in CMakeLists.txt.
2. Afterwards, as I was trying to source-install the package, I discovered that the package would not `catkin build` without …

Fix for missing icp_odometry node for install targets and message generation

---

CMakeLists.txt
package.xml

As noted by Dirk Thomas in ros2/rosidl#441, libraries for generated
interfaces must use ${PROJECT_NAME} as their basename.  This PR
modifies rtabmap_ros so that it does so.
It also tweaks a couple of rosdep keys because nav2_common was used in
some launch files but not included, and message_runtime does not exist
in ROS 2.
Fixes #397

Use project name as basename for interfaces

---

src/CoreWrapper.cpp
src/OdometryROS.cpp

Hi. While following the README in the "ros2" branch I faced two issues. The first one regards the PCL version. For PCL version equals or greater than 10.1, the change made in 'src/OdometryROS.cpp' is necessary, which is the same modification made to fix #450 but in the "melodic" branch. Second, the latest version of RTAB-LIB (v0.20.3) has changed the variable type of the method 'graph::findNearestNodes', which justifies the modification made in 'src/CoreWrapper.cpp' (please refer to #470).
After these changes, I could successfully build RTAB-LIB ROS2 (Eloquent) package. I appreciated if you could check it! 
Thanks!

updating files to build ros package with rtab-map lib v0.20.3

---

CMakeLists.txt
package.xml

As used in the CMakeLists.txt: https://github.com/introlab/rtabmap_ros/blob/ros2/CMakeLists.txt#L81

Add missing dependency on rviz_common

---

launch/ros2/realsense_d400.launch.py
launch/ros2/turtlebot3_rgbd.launch.py
launch/ros2/turtlebot3_rgbd_sync.launch.py
launch/ros2/turtlebot3_scan.launch.py

node_executable is deprecated as of [Foxy](https://docs.ros.org/en/foxy/Releases/Release-Foxy-Fitzroy.html#node-name-and-namespace-parameters-changed)

node_executable is deprecated

---

CMakeLists.txt
src/PointCloudAggregatorNode.cpp

I noticed I could not do `rosrun rtabmap_ros point_cloud_aggregator` under ros noetic.
Seems it wasn't added as executable.

Add aggregator executable

---

include/rtabmap_ros/CoreWrapper.h
src/CoreWrapper.cpp

```cpp
CoreWrapper::CoreWrapper(const rclcpp::NodeOptions & options) : ... {
....
double tfDelay = 0.05; // 20 Hz
double tfTolerance = 0.1; // 100 ms
...
transformThread_ = new std::thread([&](){
// the thread's lifetime is longer than the constructed function.
// using a local variable of the stack in the new thread
if(tfDelay == 0)
return;
....
// using a local variable of the stack in the new thread
rclcpp::Time tfExpiration = now() + rclcpp::Duration(tfTolerance*10e9);
}
}
```

fix possible stackunderflow in CoreWrapper constructed function

---

CMakeLists.txt

I made these modifications to be able to build `rtabmap-ros` without rviz support.
Please have a look, feel free to fix this otherwise. Why I needed this, was to be able to run `rtabmap-ros` on our robot, which does not have rviz installed.

Fix logic when building without rviz.

---

src/CameraNode.cpp
src/MapOptimizerNode.cpp
src/costmap_2d/static_layer.cpp
src/costmap_2d/voxel_layer.cpp
src/nodelets/data_odom_sync.cpp
src/nodelets/data_throttle.cpp
src/nodelets/rgbdicp_odometry.cpp
src/nodelets/stereo_odometry.cpp
src/nodelets/stereo_throttle.cpp

Some more occurrences of `boost::bind` which can be replaced by `std::bind`.

Replace boost::bind by std::bind.

---

src/nodelets/point_cloud_aggregator.cpp

We had a segfault using `point_cloud_aggregator`.
This patch fixed it.

[point_cloud_aggregator] pointrow_step of tmp_output should depend on size of tmp_output

---

package.xml

I was trying to grasp which dependencies where required for `rtabmap_ros`. 
Almost all of them where listed as `<build_depend>` **and** `<run depend>`. This can be a single `<depend>`.
I took the liberty of cleaning these, so it is quickly clear which dependencies are only runtime.

List dependencies only once

---

CMakeLists.txt
include/rtabmap_ros/CommonDataSubscriberDefines.h
src/CameraNode.cpp
src/CoreWrapper.cpp
src/GuiWrapper.cpp
src/costmap_2d/static_layer.cpp
src/costmap_2d/voxel_layer.cpp
src/costmap_2d/voxel_markers.cpp
src/nodelets/data_odom_sync.cpp
src/nodelets/data_throttle.cpp
src/nodelets/point_cloud_aggregator.cpp
src/nodelets/point_cloud_assembler.cpp
src/nodelets/point_cloud_xyz.cpp
src/nodelets/point_cloud_xyzrgb.cpp
src/nodelets/pointcloud_to_depthimage.cpp
src/nodelets/rgb_sync.cpp
src/nodelets/rgbd_odometry.cpp
src/nodelets/rgbd_sync.cpp
src/nodelets/rgbdicp_odometry.cpp
src/nodelets/stereo_odometry.cpp
src/nodelets/stereo_sync.cpp
src/nodelets/stereo_throttle.cpp
src/rviz/MapGraphDisplay.cpp

`$ENV{ROS_ROOT}/core/rosbuild/FindPkgConfig.cmake` doesn't exist on 22.04, though `rosbuild` provides /usr/share/ros/core/rosbuild/FindPkgConfig.cmake- but I found not doing the include at all also worked (maybe because I have `cmake-data` installed which also provides a FindPkgConfig.cmake).
The line lengths get really long with all the `boost::placeholders`, I can make another pass to bring those down.

Boost placeholders and optional FindPkgConfig.cmake to build on Ubuntu 22.04

---

CMakeLists.txt
src/MsgConversion.cpp

These minor changes remove the endless stream of warnings when [PCL is NOT a system included dir in cmake](https://github.com/PointCloudLibrary/pcl/issues/2303#issuecomment-1013668713) as well as updating tf2 includes to use .hpp instead of .h to remove warns.
This results in a clean colcon build with no errors on 22.04 ROS2 Humble.

Fix PCL warns and .hpp warns.

---

README.md

I had a similar error as referenced in #613. It turns out that I had missing dependencies which got fixed when I ran `rosdep install --from-paths src --ignore-src -r -y`. This was mentioned [here](https://github.com/introlab/rtabmap_ros/issues/613#issuecomment-922550063).

`ros2-branch` build failed when I did not run rodep install.

---

rtabmap_costmap_plugins/CMakeLists.txt
rtabmap_costmap_plugins/package.xml
rtabmap_demos/package.xml
rtabmap_examples/package.xml
rtabmap_launch/CMakeLists.txt
rtabmap_launch/package.xml
rtabmap_legacy/package.xml
rtabmap_msgs/CMakeLists.txt
rtabmap_ros/CMakeLists.txt
rtabmap_ros/package.xml
rtabmap_viz/CMakeLists.txt

I just tried building latest on Ubuntu 22.10 and got
```
In file included from /home/lucasw/base_catkin_ws/src/other/rtabmap_ros/rtabmap_viz/include/rtabmap_viz/PreferencesDialogROS.h:32,
from /home/lucasw/base_catkin_ws/src/other/rtabmap_ros/rtabmap_viz/src/PreferencesDialogROS.cpp:28:
/home/lucasw/base_catkin_ws/devel/include/rtabmap-0.21/rtabmap/gui/PreferencesDialog.h:33:10: fatal error: QDialog: No such file or directory
33 | #include <QDialog>
|          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rtabmap_viz.dir/build.make:104: CMakeFiles/rtabmap_viz.dir/src/PreferencesDialogROS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/lucasw/base_catkin_ws/src/other/rtabmap_ros/rtabmap_viz/src/GuiNode.cpp:31:10: fatal error: QApplication: No such file or …
```

build rtabmap_viz with Qt5 on Ubuntu 22.10

---

rtabmap_util/CMakeLists.txt
rtabmap_util/package.xml

This adds a missing dependency on nav_msgs to `rtabmap_utils`. This seems to be causing a build failure on ~all~ 2 out of 3 platforms on the buildfarm.
https://build.ros.org/job/Nbin_uF64__rtabmap_util__ubuntu_focal_amd64__binary/2/console
```
23:14:12 [ 20%] Building CXX object CMakeFiles/rtabmap_data_player.dir/src/DbPlayerNode.cpp.o
23:14:12 /usr/lib/ccache/c++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"rtabmap_util\" -DWITH_OCTOMAP_MSGS -I/tmp/binarydeb/ros-noetic-rtabmap-util-0.21.1/include -I/opt/ros/noetic/include -I/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/noetic/include/rtabmap-0.21 -I/usr/include/opencv4 -I/usr/include/eigen3 -I/usr/include/pcl-1.10 -I/usr/include/vtk-7.1 -I/usr/include/freetype2 -I/usr/include/ni …
```

Add dependency on nav_msgs

---

rtabmap_slam/src/CoreWrapper.cpp
rtabmap_util/CMakeLists.txt
rtabmap_util/include/rtabmap_util/MapsManager.h
rtabmap_util/package.xml
rtabmap_util/src/MapsManager.cpp
rtabmap_util/src/nodelets/obstacles_detection.cpp

See https://github.com/introlab/rtabmap/issues/1175

GridMap integration

---

rtabmap_sync/src/nodelets/rgbdx_sync.cpp

This fixes a regression in Noetic. All the `rtabmap_ros` binary jobs in Noetic are failing with the following error:
```
18:59:28 /opt/ros/noetic/include/ros/console.h:351:176: error: format not a string literal and no format arguments [-Werror=format-security]
...
18:59:28 /tmp/binarydeb/ros-noetic-rtabmap-sync-0.21.3/src/nodelets/rgbdx_sync.cpp:167:3: note: in expansion of macro ‘NODELET_INFO’
18:59:28   167 |   NODELET_INFO(subscribedTopicsMsg.c_str());
18:59:28       |   ^~~~~~~~~~~~
```
https://build.ros.org/job/Nbin_uF64__rtabmap_sync__ubuntu_focal_amd64__binary/6
Note I edited this in the github UI. I haven't built this locally.

Fix format security error in rgbdx_sync.cpp

---

rtabmap_conversions/src/MsgConversion.cpp

According to the issue #1138, I add the validation check for scan message here.

add validation check for scan-message

---

rtabmap_conversions/src/MsgConversion.cpp
rtabmap_slam/src/CoreWrapper.cpp

(cherry picked from commit 097cab06677e4618ef0e4132cc544bc319d1d9a6)
This issue also appears in ros1. For example, when RGBDImage message is published directly, only its header's seq is automatically filled. The header's seq of sub-messages, such as CameraInfo, is not automatically filled.

Fixed node ID=0 issues as msgs may not have seq.

---

rtabmap_conversions/src/MsgConversion.cpp
rtabmap_demos/launch/turtlebot4_ignition_demo.launch.py
rtabmap_demos/launch/turtlebot4_slam.launch.py
rtabmap_examples/launch/depthai.launch.py
rtabmap_examples/launch/realsense_d400.launch.py
rtabmap_examples/launch/realsense_d435i_color.launch.py
rtabmap_examples/launch/realsense_d435i_infra.launch.py
rtabmap_examples/launch/realsense_d435i_stereo.launch.py
rtabmap_examples/launch/vlp16.launch.py
rtabmap_examples/launch/zed.launch.py
rtabmap_launch/launch/rtabmap.launch.py
rtabmap_odom/include/rtabmap_odom/OdometryROS.h
rtabmap_odom/src/ICPOdometryNode.cpp
rtabmap_odom/src/OdometryROS.cpp
rtabmap_odom/src/RGBDOdometryNode.cpp
rtabmap_odom/src/StereoOdometryNode.cpp
rtabmap_odom/src/nodelets/icp_odometry.cpp
rtabmap_odom/src/nodelets/rgbd_odometry.cpp
rtabmap_odom/src/nodelets/stereo_odometry.cpp
rtabmap_slam/src/CoreWrapper.cpp
rtabmap_sync/src/CommonDataSubscriber.cpp
rtabmap_sync/src/nodelets/rgb_sync.cpp
rtabmap_sync/src/nodelets/rgbd_sync.cpp
rtabmap_sync/src/nodelets/rgbdx_sync.cpp
rtabmap_sync/src/nodelets/stereo_sync.cpp
rtabmap_util/src/nodelets/disparity_to_depth.cpp
rtabmap_util/src/nodelets/pointcloud_to_depthimage.cpp
rtabmap_util/src/nodelets/rgbd_split.cpp
rtabmap_viz/src/GuiWrapper.cpp

Addressing https://github.com/introlab/rtabmap_ros/issues/1205, https://github.com/introlab/rtabmap_ros/issues/1054

ROS2: Fixing topic sync lagging and delay issues

---

rtabmap_util/src/nodelets/point_cloud_aggregator.cpp

Queue size parameter was split into sync_queue_size and topic_queue_size parameters in ae44e1a2157b84e67ade530f2b8e713eac9650e8, however syncQueueSize was never used in PointCloudAggregator.

Make sure to use syncQueueSize for sync policies in PointCloudAggregator

---

rtabmap_examples/launch/realsense_d435i_color.launch.py
rtabmap_examples/launch/realsense_d435i_infra.launch.py
rtabmap_examples/launch/realsense_d435i_stereo.launch.py

Not sure which realsense-ros version made these namespace changes, but the examples don't work anymore.
resolves [this](https://github.com/introlab/rtabmap_ros/issues/1221#issuecomment-2417042149).
Could we port these back to the older distros as well please?

update realsense examples for ros2

---

rtabmap_util/src/nodelets/point_cloud_assembler.cpp

Bonjour de Sherbrooke Mathieu,
Since calbackCloud() is the only callback when called while using tf instead of odom in this node, the callbackCalled_ variable is never set to true, so the warning keeps spinning. Therefore, I added the variable to calbackCloud()  and removed a useless condition within the warning loop.
Please let me know if the fixes are correct.

Fixed callbackCloud warning

---

rtabmap_odom/src/nodelets/rgbd_odometry.cpp

Currently, there's just a single image transport parameter, which practically cannot be set to anything other than `raw`, since depth cannot be transported using `compressed` and color can't use `compressedDepth` either.
This PR separates the `image_transport` parameter into two, `rgb_transport` and `depth_transport`, which will allow for compressed input.
Note: There's also an unrelated change that introduces the call to `resolve_topic_or_service_name` prior to subscribing, which allows the user to remap all compressed topics by specifying just a single /image_raw remapping.

RGBD odometry: separate rgb_transport and depth_transport params

---

rtabmap_slam/CMakeLists.txt
rtabmap_slam/include/rtabmap_slam/CoreWrapper.h
rtabmap_slam/package.xml
rtabmap_slam/src/CoreWrapper.cpp

See https://github.com/introlab/rtabmap/issues/377
Aruco generator: https://chev.me/arucogen/
Camera:
```
ros2 launch rtabmap_examples realsense_d435i_infra.launch.py
```
* For [aruco_msgs](https://github.com/pal-robotics/aruco_ros) (Original Aruco marker dictionary should be used):
```
ros2 run aruco_ros marker_publisher --ros-args \
-r  camera_info:=/camera/infra1/camera_info \
-r image:=/camera/infra1/image_rect_raw \
-p marker_size:=0.11 \
-p camera_frame:=camera_infra1_optical_frame \
-r marker_publisher/markers:=aruco/detections
```
* For [aruco_opencv_msgs](https://github.com/fictionlab/ros_aruco_opencv):
```
ros2 run aruco_opencv aruco_tracker --ros-args  \
-p cam_base_topic:=/camera/infra1/image_rect_raw \
-p marker_size:=0.11 \
-p image_is_rectified:=true \
-p …
```

Adding aruco msgs input support

---

rtabmap_odom/include/rtabmap_odom/OdometryROS.h
rtabmap_odom/src/OdometryROS.cpp
rtabmap_odom/src/nodelets/icp_odometry.cpp
rtabmap_slam/src/CoreWrapper.cpp
rtabmap_sync/include/rtabmap_sync/SyncDiagnostic.h

When the clock is jumping in the past (for some reason: ntp sync or something) while visual odometry (vo) is running, vo will detect non incremental timestamps, then skip all new frames till a new frame has stamp higher than latest added frame. If the jump is 10 seconds in the past, it means VO won't update for 10 seconds. We added that check in the past for rosbags having flaky sensor data where sometimes topics would arrived unordered. However, if it is caused by a clock jump, we should reset as soon as possible. This PR is doing that, while still skipping frames in case of flaky input data stream (not related to clock jumping).

Odom reset on time jump in the past

---

.devcontainer/humble/Dockerfile
.devcontainer/jazzy/Dockerfile
.devcontainer/kilted/Dockerfile
rtabmap_odom/src/nodelets/rgbd_odometry.cpp
rtabmap_odom/src/nodelets/stereo_odometry.cpp
rtabmap_slam/src/CoreWrapper.cpp
rtabmap_sync/include/rtabmap_sync/CommonDataSubscriber.h
rtabmap_sync/src/CommonDataSubscriber.cpp
rtabmap_sync/src/impl/CommonDataSubscriberDepth.cpp
rtabmap_sync/src/impl/CommonDataSubscriberRGB.cpp
rtabmap_sync/src/impl/CommonDataSubscriberStereo.cpp
rtabmap_sync/src/nodelets/rgb_sync.cpp
rtabmap_sync/src/nodelets/rgbd_sync.cpp
rtabmap_sync/src/nodelets/stereo_sync.cpp
rtabmap_util/src/nodelets/point_cloud_xyz.cpp
rtabmap_util/src/nodelets/point_cloud_xyzrgb.cpp

Unified the way to set `image_transport` and `depth_transport` for all nodes subscribing to image topics with `image_transport` subscribers. We can launch nodes with:
`-p image_transport:="compressed" -p depth_transport:="depthCompressed"` to use respective `image_transport` plugins. 
To make `image_transport` parameter resolvable by `image_transport::TransportHints` is to pre-declare that parameter before creating the hint. 
Examples:
```
ros2 run rtabmap_slam rtabmap -d --ros-args \
-p image_transport:=compressed \
-p depth_transport:=compressedDepth
[...]
rtabmap subscribed to (approx sync):
/odom \
/rgb/image/compressed \
/depth/image/compressedDepth \
/rgb/camera_info
```
```
ros2 run rtabmap_slam rtabmap -d --ros-args \
-p subscribe_stereo:=true \
-p image_transport:=compressed …
```

Resolving image_transport hints support (#1181)
